---
- name: 
  hosts: localhost
  gather_facts: no
  vars_files:
    - vm-vars.yml
    - vmware-admin-vars.yml
  vars_prompt:
    - name: os_type
      prompt: "Is this Linux or Windows"
      private: no
    - name: vm
      prompt: "What is the requested name for this VM?"
      private: no

  tasks:
    - name: Create Widows VM - {{ vm_name }}
      include_tasks: tsk-vm-from-template.yml
      vars:
        custom_spec: Lab_windows2019
        vm_template: T_WIN2019_ANS
        vm_name: "{{ vm }}"
      when: os_type is match("[wW]indows")

    - name: Create Linux VM - {{ vm_name }}
      debug: 
        msg: "We are creating the {{ vm_name }} as a Linux VM"
      when: os_type is match("[lL]inux")


    - name: Do Not Create VM - {{ vm_name }}
      debug:
        msg: "You entered {{ os_type }} which is neither Windows or Linux"
      when: os_type is not match("[wW]indows") and os_type is not match("[lL]inux")  
