- name: DSC Configure host
  hosts:  win_nodes
    tasks:
      
      - name: Install IIS Web-Server with sub features and management tools
          win_feature:
          name: Web-Server
          state: present
          include_sub_features: yes
          include_management_tools: yes
        register: win_feature

